export const robots = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "sincere@april.biz",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "shanna@melissa.tv",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "nathan@yesenia.net",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "julianne.OConner@kory.org",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "lucio_Hettinger@annie.ca",
  },
  {
    id: 6,
    name: "Sr. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "karley_Dach@jasper.info",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "telly.Hoeger@billy.biz",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "sherwood@rosamond.me",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "chaim_McDermott@dana.io",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "rey.Padberg@karina.biz",
  },
  {
    id: 11,
    name: "Aiden Webster",
    username: "Romeostern",
    email: "bessyhardasarock@sbcglobal.net",
  },
  {
    id: 12,
    name: "Josiah Mackay",
    username: "Tractorbenefits",
    email: "lennystalker@me.com",
  },
  {
    id: 13,
    name: "Aariz Salinas",
    username: "Batteryfake",
    email: "geoffplayer@me.com",
  },
  {
    id: 14,
    name: "Yousef Reynolds",
    username: "Momfill",
    email: "babswierd@optonline.net",
  },
  {
    id: 15,
    name: "Teejay Churchill",
    username: "Worksuspense",
    email: "arousedmoishy@sbcglobal.net",
  },
  {
    id: 16,
    name: "Joy Lawson",
    username: "Shabbyquilp",
    email: "regretfulmoe@live.com",
  },
  {
    id: 17,
    name: "Aimie Mcnamara",
    username: "Clipperswoolwich",
    email: "awkwardvikki@aol.com",
  },
  {
    id: 18,
    name: "Laila Morgan",
    username: "Wonhonored",
    email: "shamedcassie@sbcglobal.net",
  },
  {
    id: 19,
    name: "Clementina DuBuque",
    username: "Grazingstrung",
    email: "jabdetermined@msn.com",
  },
  {
    id: 20,
    name: "Annabel Wharton",
    username: "Fennelkickin",
    email: "disarmshiny@icloud.com",
  },
  {
    id: 21,
    name: "Lavinia Ryan",
    username: "Crashborough",
    email: "seizedelectable@me.com",
  },
  {
    id: 22,
    name: "Trent Floyd",
    username: "Testergroom",
    email: "splinteroffbeat@verizon.net",
  },
  {
    id: 23,
    name: "Keane Nixon",
    username: "Hookgong",
    email: "stuserious@optonline.net",
  },
  {
    id: 24,
    name: "Jillian Werner",
    username: "Evidentfroaking",
    email: "hanklooser@mac.com",
  },
  {
    id: 25,
    name: "Giovanni Mccallum",
    username: "Lookupquest",
    email: "tessmadcow@icloud.com",
  },
  {
    id: 26,
    name: "Sarah-Jane Hatfield",
    username: "Shirtcoil",
    email: "reggierowdy@yahoo.com",
  },
  {
    id: 27,
    name: "Pablo Duffy",
    username: "Companyhandsaw",
    email: "revulsionliz@yahoo.com",
  },
  {
    id: 28,
    name: "Pablo Duffy",
    username: "Berylliummeiosis",
    email: "numbsuzy@icloud.com",
  },
  {
    id: 29,
    name: "Margaux Keenan",
    username: "Crunchingtinker",
    email: "intriguedthom@outlook.com",
  },
  {
    id: 30,
    name: "Avni Connolly",
    username: "Muffledhowdy",
    email: "annoyedlou@yahoo.com",
  },
  {
    id: 31,
    name: "Makayla Osborne",
    username: "Enrickmolecular",
    email: "spreadstimulating@protonmail.com",
  },
  {
    id: 32,
    name: "Bushra Tanner",
    username: "Odnoklassnikiopal",
    email: "standardizeorderly@icloud.com",
  },
  {
    id: 33,
    name: "Libbie Gates",
    username: "Jaybirdsulfurn",
    email: "subsidejuicy@gmail.com",
  },
  {
    id: 34,
    name: "Ashlyn Read",
    username: "Faxfrog",
    email: "hustletidy@yahoo.com",
  },
  {
    id: 35,
    name: "Valerie Carlson",
    username: "Dudgeonpromethium",
    email: "moistengrizzled@gmail.com",
  },
  {
    id: 36,
    name: "Traci Reilly",
    username: "Latterroar",
    email: "sacrificefunctional@mac.com",
  },
  {
    id: 37,
    name: "Jeremy Hess",
    username: "Grievinginformation",
    email: "protestsmoggy@yahoo.ca",
  },
  {
    id: 38,
    name: "Amanah Pena",
    username: "Musteringanthology",
    email: "administerrevolving@live.com",
  },
  {
    id: 39,
    name: "Olli Crawford",
    username: "Cornstalkplumbing",
    email: "boreworldly@optonline.net",
  },
  {
    id: 40,
    name: "Seren Sierra",
    username: "Varicosepeck",
    email: "sharpenlumbering@me.com",
  },
  {
    id: 41,
    name: "Ellie Hubbard",
    username: "Alertstweed",
    email: "bawlsure-footed@mac.com",
  },
  {
    id: 42,
    name: "Campbell Best",
    username: "Escalatorsconny",
    email: "barbecuecircular@sbcglobal.net",
  },
  {
    id: 43,
    name: "Dhruv Campbell",
    username: "Eurorepent",
    email: "declineorganic@optonline.net",
  },
  {
    id: 44,
    name: "Ksawery Singh",
    username: "Confirmfoe",
    email: "exceedagreeable@verizon.net",
  },
  {
    id: 45,
    name: "Zahraa O'Reilly",
    username: "Descentinquire",
    email: "rethinksneaky@yahoo.com",
  },
  {
    id: 46,
    name: "Alicja Camacho",
    username: "Overpaybakeshop",
    email: "restrainicky@comcast.net",
  },
  {
    id: 47,
    name: "Karim Justice",
    username: "Shipmulled",
    email: "dwindlesvelte@me.com",
  },
  {
    id: 48,
    name: "Albert Santana",
    username: "Granolapucker",
    email: "preoccupypuzzled@optonline.net",
  },
  {
    id: 49,
    name: "Effie Mullen",
    username: "Scoringcapping",
    email: "ceasemixed@att.net",
  },
  {
    id: 50,
    name: "Mariya Hernandez",
    username: "Emmaprankster",
    email: "embossmonstrous@gmail.com",
  },
  {
    id: 51,
    name: "Duane Schwartz",
    username: "Fiscallylist",
    email: "cloudtragic@outlook.com",
  },
  {
    id: 52,
    name: "Ziggy Millington",
    username: "Seriesrework",
    email: "patronizeembellished@yahoo.com",
  },
];
